-- 2026-08-20b-STEP1-preview-non-mouseion-skills.sql
-- Read-only. Run this FIRST, look at the numbers, and only then run
-- 2026-08-20b-STEP2-delete-non-mouseion-skills.sql.

SELECT 'skills to remove' AS what, COUNT(*) AS n FROM skills WHERE name IN (
  'Abstract Reasoning',
  'Attention & Focus',
  'Research & Inquiry',
  'Mathematical Literacy',
  'Scientific Method',
  'Imagination & Conceptual Thinking',
  'Writing',
  'Non-Verbal Communication',
  'Digital Communication',
  'Stress Management',
  'Motivation & Self-Drive',
  'Boundary Setting',
  'Sports & Athletic Skills',
  'Instrument Playing',
  'Nutrition & Health Literacy',
  'Community Building',
  'Networking & Relationship Building',
  'Photography & Film',
  'Programming & Coding',
  'Cybersecurity Awareness',
  'AI & Automation Literacy',
  'Engineering & Systems Design',
  'Financial Literacy',
  'Household & DIY Management',
  'Time & Energy Management',
  'Environmental Stewardship',
  'Ethical Reasoning',
  'Mindfulness & Contemplation',
  'Meaning-Making & Purpose',
  'Philosophical Inquiry',
  'Spiritual Practice',
  'Feedback Integration',
  'Habit Formation',
  'Adaptability & Flexibility'
)
UNION ALL
SELECT 'learner_skill_progress rows', COUNT(*) FROM learner_skill_progress
  WHERE skill_id IN (SELECT id FROM skills WHERE name IN ('Abstract Reasoning',
  'Attention & Focus',
  'Research & Inquiry',
  'Mathematical Literacy',
  'Scientific Method',
  'Imagination & Conceptual Thinking',
  'Writing',
  'Non-Verbal Communication',
  'Digital Communication',
  'Stress Management',
  'Motivation & Self-Drive',
  'Boundary Setting',
  'Sports & Athletic Skills',
  'Instrument Playing',
  'Nutrition & Health Literacy',
  'Community Building',
  'Networking & Relationship Building',
  'Photography & Film',
  'Programming & Coding',
  'Cybersecurity Awareness',
  'AI & Automation Literacy',
  'Engineering & Systems Design',
  'Financial Literacy',
  'Household & DIY Management',
  'Time & Energy Management',
  'Environmental Stewardship',
  'Ethical Reasoning',
  'Mindfulness & Contemplation',
  'Meaning-Making & Purpose',
  'Philosophical Inquiry',
  'Spiritual Practice',
  'Feedback Integration',
  'Habit Formation',
  'Adaptability & Flexibility'))
UNION ALL
SELECT 'sessions rows (primary_skill_id -- these sessions get deleted, not just unlinked)', COUNT(*) FROM sessions
  WHERE primary_skill_id IN (SELECT id FROM skills WHERE name IN ('Abstract Reasoning',
  'Attention & Focus',
  'Research & Inquiry',
  'Mathematical Literacy',
  'Scientific Method',
  'Imagination & Conceptual Thinking',
  'Writing',
  'Non-Verbal Communication',
  'Digital Communication',
  'Stress Management',
  'Motivation & Self-Drive',
  'Boundary Setting',
  'Sports & Athletic Skills',
  'Instrument Playing',
  'Nutrition & Health Literacy',
  'Community Building',
  'Networking & Relationship Building',
  'Photography & Film',
  'Programming & Coding',
  'Cybersecurity Awareness',
  'AI & Automation Literacy',
  'Engineering & Systems Design',
  'Financial Literacy',
  'Household & DIY Management',
  'Time & Energy Management',
  'Environmental Stewardship',
  'Ethical Reasoning',
  'Mindfulness & Contemplation',
  'Meaning-Making & Purpose',
  'Philosophical Inquiry',
  'Spiritual Practice',
  'Feedback Integration',
  'Habit Formation',
  'Adaptability & Flexibility'))
UNION ALL
SELECT 'verified_skills rows', COUNT(*) FROM verified_skills
  WHERE skill_id IN (SELECT id FROM skills WHERE name IN ('Abstract Reasoning',
  'Attention & Focus',
  'Research & Inquiry',
  'Mathematical Literacy',
  'Scientific Method',
  'Imagination & Conceptual Thinking',
  'Writing',
  'Non-Verbal Communication',
  'Digital Communication',
  'Stress Management',
  'Motivation & Self-Drive',
  'Boundary Setting',
  'Sports & Athletic Skills',
  'Instrument Playing',
  'Nutrition & Health Literacy',
  'Community Building',
  'Networking & Relationship Building',
  'Photography & Film',
  'Programming & Coding',
  'Cybersecurity Awareness',
  'AI & Automation Literacy',
  'Engineering & Systems Design',
  'Financial Literacy',
  'Household & DIY Management',
  'Time & Energy Management',
  'Environmental Stewardship',
  'Ethical Reasoning',
  'Mindfulness & Contemplation',
  'Meaning-Making & Purpose',
  'Philosophical Inquiry',
  'Spiritual Practice',
  'Feedback Integration',
  'Habit Formation',
  'Adaptability & Flexibility'))
UNION ALL
SELECT 'arts_skills rows', COUNT(*) FROM arts_skills
  WHERE skill_id IN (SELECT id FROM skills WHERE name IN ('Abstract Reasoning',
  'Attention & Focus',
  'Research & Inquiry',
  'Mathematical Literacy',
  'Scientific Method',
  'Imagination & Conceptual Thinking',
  'Writing',
  'Non-Verbal Communication',
  'Digital Communication',
  'Stress Management',
  'Motivation & Self-Drive',
  'Boundary Setting',
  'Sports & Athletic Skills',
  'Instrument Playing',
  'Nutrition & Health Literacy',
  'Community Building',
  'Networking & Relationship Building',
  'Photography & Film',
  'Programming & Coding',
  'Cybersecurity Awareness',
  'AI & Automation Literacy',
  'Engineering & Systems Design',
  'Financial Literacy',
  'Household & DIY Management',
  'Time & Energy Management',
  'Environmental Stewardship',
  'Ethical Reasoning',
  'Mindfulness & Contemplation',
  'Meaning-Making & Purpose',
  'Philosophical Inquiry',
  'Spiritual Practice',
  'Feedback Integration',
  'Habit Formation',
  'Adaptability & Flexibility'));
